version: '3'

services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul-server
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
    networks:
      - consul-net
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 5s
      retries: 3

  fake-service:
    image: nicholasjackson/fake-service:v0.24.2
    container_name: fake-service
    ports:
      - "8080:8080"
    environment:
      - LISTEN_ADDR=0.0.0.0:8080
      - NAME=my-service
      - MESSAGE=Hello World
      - SERVER_TYPE=http
      - HEALTH_CHECK_URL=/health
    networks:
      - consul-net
    depends_on:
      consul:
        condition: service_healthy

networks:
  consul-net:
    # Specify driver options
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"